apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-minute
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo I will conquer the world
          restartPolicy: OnFailure