apiVersion: v1
kind: ReplicationController
metadata:
  name: website
spec:
  replicas: 2
  selector:
    app: website
  template:
    metadata:
      name: website
      labels:
        app: website
    spec:
      containers:
        - name: website-nginx
          image: nginx
          ports:
            - containerPort: 80
