apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
      matchLabels:
        app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: dragomiralin/order-microservice:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/order
	  imagePullPolicy: Always
