apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      name: ssd-monitor
  template:
    metadata:
      labels:
        name: ssd-monitor
    spec:
      nodeSelector:
        disk: ssd
      containers:
        - name: ssd-monitor
          image: luksa/ssd-monitor
          ports:
            - containerPort: 80
